
services:
  frontend:
    build:
      context: ./client  
    ports:
      - "3000:80"  
    networks:
      - app-network
    depends_on:
      - server  

  server:
    build:
      context: ./server  
    ports:
      - "8080:8080"  
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./server:/app  
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
